:toc: left
:backend: pdf
:doctitle: Living Documentation
:doctype: book
:icons: font
:!numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: coderay
:toclevels: 3
:hardbreaks:
:chapter-label: Chapter
:version-label: Version

= *Living Documentation*

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 2

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<Parcours-de-recherche-d'un-article>>*
|1
|0
|1
|3
|0
|0
|0
|0
|0
|3
|002ms
|[green]#*passed*#

12+^|*<<Shopping>>*
|2
|0
|2
|6
|0
|0
|0
|0
|0
|6
|050ms
|[green]#*passed*#
12+^|*Totals*
|3|0|3|9|0|0|0|0|0|9 2+|053ms
|===

== *Features*

[[Parcours-de-recherche-d'un-article, Parcours de recherche d'un article]]
=== *Parcours de recherche d'un article*

==== Scénario: Recherche d'un article connu

==========
Etant donné que ::
je connais déjà l'article icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
Lorsque ::
je le cherche dans les rayons icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
Alors ::
je le trouve à sa place icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
==========

[[Shopping, Shopping]]
=== *Shopping*

==== Scenario: Track my budget

==========
Given ::
I have 100 in my wallet icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
When ::
I buy milk with 10 icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
Then ::
I should have 90 in my wallet icon:thumbs-up[role="green",title="Passed"] [small right]#(049ms)#
==========

==== Scenario: Track my budget

==========
Given ::
I have 200 in my wallet icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
When ::
I buy rice with 20 icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
Then ::
I should have 180 in my wallet icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
==========

